### ISSUE TITLE
Indicate post a reply refers to

### ISSUE THREAD

**Issue by Pohli** [szopin/harbour-sfos-forum-viewer#11]
There are general replies and also replies to specific previous posts. Right now both kinds can't be distinguished from each other. In the latter case it should be somehow indicated to which post a reply refers to. Maybe show a link to jump back to the referring post and then highlight that post like it's done in the html version.

**Comment by szopin** [comment]
It's problematic as you can quote as many posts as you want in a post, json contains only one post number (and not even sure if this is updated vs deleted posts, search results for example are not), to get the others you would need to parse the html/cooked part to pull all post numbers... Example:
`"<aside class=\"quote no-group\" data-username=\"DaveRo\" data-post=\"2\" data-topic=\"1114\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img alt=\"\" width=\"20\" height=\"20\" src=\"https://forum.sailfishos.org/letter_avatar_proxy/v4/letter/d/838e76/40.png\" class=\"avatar\"> DaveRo:</div>\n<blockquote>\n<p>A post may reply to several posts, too.</p>\n</blockquote>\n</aside>\n<aside class=\"quote no-group\" data-username=\"peterleinchen\" data-post=\"3\" data-topic=\"1114\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img alt=\"\" width=\"20\" height=\"20\" src=\"https://forum.sailfishos.org/user_avatar/forum.sailfishos.org/peterleinchen/40/39_2.png\" class=\"avatar\"> peterleinchen:</div>\n<blockquote>\n<p>Are you sure? (how could one do that?)</p>\n</blockquote>\n</aside>\n<p>I see a quote is not a treated as a reply, so no.</p>"`
This is how browser generates the expand/scroll to options next to quotes. Might add an option to scroll to the replied post (from json) if it actually updates when posts are replied, the other... probably not as don't see a good way to implement it for arbitrary number of quotes

**Comment by szopin** [comment]
Got it working like... half of the time, the other half it scrolls in a twitchy manner, bug reported to jolla (https://forum.sailfishos.org/t/silicalistview-postitionviewatindex-from-contextmenu-buggy-behaviour/1434), if they fix it or provide some kind of reliable workaround will come back to it

**Comment by szopin** [comment]
Closing for now, if a workaround is posted or a fix in the Silica library will reopen, atm no point in having this hanging
