### ISSUE TITLE
Emoticons are too big

### ISSUE THREAD

**Issue by Pohli** [szopin/harbour-sfos-forum-viewer#12]
Smilies are like three times as high as a normal text line and several characters in width. This makes big spaces between lines and words. If smilies would be smaller but not easily recognisable maybe add zoom function.

Jolla Phone with SFOS 3.0.1.11 and SFOS Forum Viewer 0.7.4

**Comment by szopin** [comment]
It's just images coming from the forum included in the post text (like `<img src=\"https://forum.sailfishos.org/images/emoji/twitter/smiley.png?v=9\"`) , there's no way we're going to keep a copy of each and at different scales for every possible sfos device

**Comment by Pohli** [comment]
> It's just images coming from the forum included in the post text (like `<img src=\"https://forum.sailfishos.org/images/emoji/twitter/smiley.png?v=9\"`) , there's no way we're going to keep a copy of each and at different scales for every possible sfos device

Now emoticons are too small. Isn’t it possible to adjust the display size of the emoticon images automatically to the text size, like in HTML?

**Comment by szopin** [comment]
I think the picture emoji's are too big, while the ones that come with sfos are too small, like with the black screen bug it's something that jolla need to fix in silica/qml, this app is just a basic qml app, using defaults that jolla provides, things like scaling elements properly for each handset and resolution needs to be handled by them
