### ISSUE TITLE
Group topics into days on topics overview page

### ISSUE THREAD

**Issue by Pohli** [szopin/harbour-sfos-forum-viewer#13]
I'm using abandoned but still working Voyager client for TJC. There the topics are grouped into Today, Yesterday, Tuesday, …, Older if today was Thursday (activity, not creation of first post). That way it's easier to find updated topics since last visit. Right now there's no way to distinguish topics with recent activity in SFOS Forum Viewer. A short time info at every topic in overview would be nice, too.

**Comment by szopin** [comment]
The only quick fix for this would be including this:

bumped_at  "2020-08-08T16:23:34.027Z"

It's the only date value in the json we can use, I can clean it a bit (like you see in threadview), but no easy way to group into days of the week etc (the 15m, 3h etc is also done browserside and it's a huge bit of recoding for very little use, if we get oauth topic tracking will be done forumside), let me know if including last bump date after number of posts would be something you'd want

**Comment by Pohli** [comment]
Yes, that would help me, too. Maybe get some opinions of other users and make it optional if too many disagreement.

**Comment by szopin** [comment]
the (posts: x) line is pretty empty so shouldn't be an issue, but sure would be better to have that format parsed into more human-friendly version like happens in browsers, just not sure if this is something that can be easily plugged into an already available functionality (like pretty easy translation of linux time as you can add/subtract etc freely) and don't see myself spending too much time on it (and it would involve timezones so yeah... no way), will add in 0.7.5

**Comment by Moppa5** [comment]
Here's some kind of wireframe of what we could probably have on the main view. Formatting the date was pretty straight forward. I used the last_activity on this but surely we could change it to "created at" or whatever is available on JSON. 
![image](http://puu.sh/Gg0nz/b81bde33e0.jpg)

**Comment by szopin** [comment]
I'm just going to use the same string.splitting as in threads view, it's quick and consistent (unless you can plug this format of yours into something for further manipulation (days passed counting etc)

On Sunday, 9 August 2020, Santeri wrote:
> Here's some kind of wireframe of what we could probably have on the main view. Formatting the date was pretty straight forward. I used the last_activity on this but surely we could change it to "created at" or whatever is available on JSON. 
> ![image](http://puu.sh/Gg0nz/b81bde33e0.jpg)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67103146

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
Something like this could be done. We could also add there some kind of indication that "Latest activity" or "Created". It only depends on the thing that what do you want to show there. 
![image](http://puu.sh/Gg0Ai/2d5ec26539.jpg)

**Comment by szopin** [comment]
Yeah just like browser, but the only thing to work with is see reply 1-2 a weird format from discourse API, if you want to spend hours just to implement some kind of handmade parsing that will change their format into minutes -> hours -> days (days of the week) - weeks -> months/years... Go for it(btw timezones are a thing and no idea if forum is cet or bst or finnish summer time or... And of course you need your device timezone and play with it too, fun fun fun), for now I'm going to just split the spring into (date time) format

On Sunday, 9 August 2020, Santeri wrote:
> Something like this could be done. We could also add there some kind of indication that "Latest activity" or "Created". It only depends on the thing that what do you want to show there. 
> ![image](http://puu.sh/Gg0Ai/2d5ec26539.jpg)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67103293

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
Sorry, couldn't quite catch your point. This parsing is already done by formatting so minutes->hours->days work and after 30 days ->months etc. no need to spend hours for that since JavaScript can already do that. Timezones etc. are good point, not sure about them either. It might be so that the formatter, that I use, uses the device local time and shows them based on that.

**Comment by szopin** [comment]
Cool, make a PR then when ready, will have a look, date alone is pretty bad, the minutes-hours... like browser does is probably the best approach (you could use subcategories... Or what's it called, generates a nice title on the right of a silicalistview, those dates could fit there to group items by date) 

On Sunday, 9 August 2020, Santeri wrote:
> Sorry, couldn't quite catch your point. This parsing is already done by formatting so minutes->hours->days work and after 30 days ->months etc. no need to spend hours for that since JavaScript can already do that. Timezones etc. are good point, not sure about them either. It might be so that the formatter, that I use, uses the device local time and shows them based on that.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67103449

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Just curious is this a built in js function or you're using third party lib for that? If the latter make sure it's not gplv3 as that is a way in for license trolls and i don't have time for that, so would be time wasted (gplv3 is incompatible with MIT soake you sure you don't borrow any of such code) 

On Sunday, 9 August 2020, Santeri wrote:
> Sorry, couldn't quite catch your point. This parsing is already done by formatting so minutes->hours->days work and after 30 days ->months etc. no need to spend hours for that since JavaScript can already do that. Timezones etc. are good point, not sure about them either. It might be so that the formatter, that I use, uses the device local time and shows them based on that.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67103449

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin, This is built in JS stuff. And no need to worry about license stuff, I work in an open source company so I wouldn't jump on using third party libs without carefully planning it before.

**Comment by szopin** [comment]
I'm really unsure what careful planning was done with pushing a buggy coverpage we've now spent hours on discussing/fixing, so whatever, just fyi, if it's gplv3 it's out, we don't need that virus here, seen what happened at zeronet 

On Sunday, 9 August 2020, Santeri wrote:
> @szopin, This is built in JS stuff. And no need to worry about license stuff, I work in an open source company so I wouldn't jump on using third party libs without carefully planning it before. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67103904

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> I'm really unsure what careful planning was done with pushing a buggy coverpage
>
Never really stated that there was some careful planning when implementing coverpage so could you just stop whining about it all the time? There was a one real bug with the coverpage and that was the "Load more" so I personally wouldn't call it "buggy" unless I wanted to be offensive. The others were just some subjective opinions as I didn't like the content behind the refresh icon and you're ok with that, I just consider that content behind as a bad design. 
> we've now spent hours on discussing/fixing
>
I don't know what you're doing if it requires hours on discussing / fixing since it didn't require for me. On the other hand, this is just part of the developing process. It really takes time and no one writes bug free code all the time. If you don't have time to review stuff, you don't merge them in the first place.  I don't see any hurry for pushing new version after version. This is your repository so you decide what you want to merge there so I don't really get the attitude of complaining after merge. Pull requests are there for a reason, it's a request. You can always test them out when you have time and review them completely. When you say you don't have time maybe you should just completely ignore any PRs.  

However, when I started developing here I suggested how we could've improved our communication but you were reluctant to take any actions. Feedback is always welcome but the feedback shouldn't be ranting and whining always about something being wrong. The second thing is that you really should elaborate yourself better. Some posts are just so cryptic that it really requires excessive questions to understand what you're really saying. Use for instance use cases when explaining, they're more understandable.

**Comment by szopin** [comment]
Yes, kanban is not happening, this is an open source project with contributors sacrificing their own free time (that includes maintainer), so no freaking way to make it corpo style, just not gonna happen. It was a known bug submitted in PR and not described in it, pls value other ppl's time, mine is very limited, so if your PR is just a prototype state so, so I won't waste time reviewing its functionality, that time could be used more productively (if fixing it took you less than an hour, just pls do that before submitting next time, it always takes longer to dredge through someone else's code), but yeah, whatever, I'm not gonna waste more time arguing

On Sunday, 9 August 2020, Santeri wrote:
> > I'm really unsure what careful planning was done with pushing a buggy coverpage
> >
> Never really stated that there was some careful planning when implementing coverpage so could you just stop whining about it all the time? There was a one real bug with the coverpage and that was the "Load more" so I personally wouldn't call it "buggy" unless I wanted to be offensive. The others were just some subjective opinions as I didn't like the content behind the refresh icon and you're ok with that, I just consider that content behind as a bad design. 
> > we've now spent hours on discussing/fixing
> >
> I don't know what you're doing if it requires hours on discussing / fixing since it didn't require for me. On the other hand, this is just part of the developing process. It really takes time and no one writes bug free code all the time. If you don't have time to review stuff, you don't merge them in the first place.  I don't see any hurry for pushing new version after version. This is your repository so you decide what you want to merge there so I don't really get the attitude of complaining after merge. Pull requests are there for a reason, it's a request. You can always test them out when you have time and review them completely. When you say you don't have time maybe you should just completely ignore any PRs.  
> 
> However, when I started developing here I suggested how we could've improved our communication but you were reluctant to take any actions. Feedback is always welcome but the feedback shouldn't be ranting and whining always about something being wrong. The second thing is that you really should elaborate yourself better. Some posts are just so cryptic that it really requires excessive questions to understand what you're really saying. Use for instance use cases when explaining, they're more understandable. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67104191

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Yes, kanban is not happening, this is an open source project with contributors sacrificing their own free time (that includes maintainer), so no freaking way to make it corpo style, just not gonna happen
>
This just contradicts everything. Kanban or some kind of roadmap on what people are doing would just save time on the larger scale. GitHub offers the Projects where issues can be linked on Kanban style board. And btw, Kanban wasn't the only solution to improve communication. 
> It was a known bug submitted in PR
> 
No it wasn't. I have never stated anywhere that it was a known bug so I don't really know where you draw that thing. I was going to fix that at the same day or next day, before I got sick and tired of your whining.
>but yeah, whatever, I'm not gonna waste more time arguing
> 
And this by the way is so ironic. Multiple times have I tried to say that could we just leave it be but no the thing just keeps going.

**Comment by szopin** [comment]
Yah except you stating: we might need to remove pageno (just accidentally the reason for the known bug), again dude, whatever, people can and will come in as and when they want, you can spend hundreds of hours on kanban, noone is your employee, they will work on what they want, good luck kanbaning that, peace

On Sunday, 9 August 2020, Santeri wrote:
> > Yes, kanban is not happening, this is an open source project with contributors sacrificing their own free time (that includes maintainer), so no freaking way to make it corpo style, just not gonna happen
> >
> This just contradicts everything. Kanban or some kind of roadmap on what people are doing would just save time on the larger scale. GitHub offers the Projects where issues can be linked on Kanban style board. And btw, Kanban wasn't the only solution to improve communication. 
> > It was a known bug submitted in PR
> > 
> No it wasn't. I have never stated anywhere that it was a known bug so I don't really know where you draw that thing. I was going to fix that at the same day or next day, before I got sick and tired of your whining.
> >but yeah, whatever, I'm not gonna waste more time arguing
> > 
> And this by the way is so ironic. Multiple times have I tried to say that could we just leave it be but no the thing just keeps going. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67104388

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Yah except you stating: we might need to remove pageno (just accidentally the reason for the known bug)
>
Posting this here yet still because you're accusing me of something that's not true. So me debugging after PR's done means that I knew it before making the PR? I don't see any logic, I see only that you want to see something. The fact that the PR was made 7 days ago and the comment about removing pageno 6 days ago quite well shows no causality of me posting  buggy CoverPage. 
> people can and will come in as and when they want, you can spend hundreds of hours on kanban, noone is your employee
>
It's no real argument to have some public plans. I don't see many people here developing this client and posting PRs thus we could well have kanban or some kind of roadmap. Nevertheless, as you stated, you are not willing to do this.

**Comment by szopin** [comment]
You had the solution "remove pageno?" at hand (me pointing out the bug day later lol), so you knew it was the issue, look why didn't you disagree last time when I said you knowingly PRed buggy code? Whatever dude, I'm out 

On Sunday, 9 August 2020, Santeri wrote:
> > Yah except you stating: we might need to remove pageno (just accidentally the reason for the known bug)
> >
> Posting this here yet still because you're accusing me of something that's not true. So me debugging after PR's done means that I knew it before making the PR? I don't see any logic, I see only that you want to see something. The fact that the PR was made 7 days ago and the comment about removing pageno 6 days ago quite well shows no causality of me posting  buggy CoverPage. 
> > people can and will come in as and when they want, you can spend hundreds of hours on kanban, noone is your employee
> >
> It's no real argument to have some public plans. I don't see many people here developing this client and posting PRs thus we could well have kanban or some kind of roadmap. Nevertheless, as you stated, you are not willing to do this.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67104651

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
Yeah, debugged it after I saw your comment day after PR. 
![image](http://puu.sh/Gg2n9/a9fdb8134a.png)
> why didn't you disagree last time when I said you knowingly PRed buggy code?
>
Because I got "fuck this shit I'm out". Why I pointed out my disagreeing now => because you brought it up again in this thread quite explicitly and it has been a week to calm down.

**Comment by szopin** [comment]
Except you had it out at first comment, you knew it, then you went defensive: i can  PR buggy code fyou, whatever dude

On Sunday, 9 August 2020, Santeri wrote:
> Yeah, debugged it after I saw your comment day after PR. 
> ![image](http://puu.sh/Gg2n9/a9fdb8134a.png)
> > why didn't you disagree last time when I said you knowingly PRed buggy code?
> >
> Because I got "fuck this shit I'm out". Why I pointed out my disagreeing now => because you brought it up again in this thread quite explicitly and it has been a week to calm down. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67104769

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Except you had it out at first comment, you knew it
>
No I didn't. Please provide evidence to backup your claims. 

What do you mean by first? You posted the first comment
![image](http://puu.sh/Gg2xF/d6359a4308.png)
![image2](http://puu.sh/Gg2y3/65f376a3f3.png)

**Comment by szopin** [comment]
I'm out, you can review the thread, waste of, but you seem to like it so go ahead

On Sunday, 9 August 2020, Santeri wrote:
> > Except you had it out at first comment, you knew it
> >
> No I didn't. Please provide evidence to backup your claims. 
> 
> What do you mean by first? You posted the first comment
> ![image](http://puu.sh/Gg2xF/d6359a4308.png)
> ![image2](http://puu.sh/Gg2y3/65f376a3f3.png)
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67104884

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> I'm out, you can review the thread, waste of, but you seem to like it so go ahead
>
I have no sympathy for someone accusing me of something that is simply not true and blaming afterwards again. This something is not first of all big deal but you made it big deal by starting whining and blaming again. 

If you make a statement about something, provide the evidence. Otherwise, you can come as you're lying. I don't see in your head and I can't review the thread and find something that doesn't exist. 

>I'm out
>
And be out then really. You can't even stand behind your own words :D

**Comment by szopin** [comment]
>whining and blaming
> you're lying
How about you review that thread where you instantly have a possible solution you lying fuck? It took me a day to get back to you, don't claim it took you a day to realise you had bugs in your implementation with a possible fix right at hand? This conversation is over, go whine somewhere else

On Sunday, 9 August 2020, Santeri wrote:
> > I'm out, you can review the thread, waste of, but you seem to like it so go ahead
> >
> I have no sympathy for someone accusing me of something that is simply not true and blaming afterwards again. This something is not first of all big deal but you made it big deal by starting whining and blaming again. 
> 
> If you make a statement about something, provide the evidence. Otherwise, you can come as you're lying. I don't see in your head and I can't review the thread and find something that doesn't exist. 
> 
> >I'm out
> >
> And be out then really. You can't even stand behind your own words :D
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105026

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> How about you review that thread where you instantly have a possible solution you lying fuck?
>
This doesn't provide me anything because I don't see that as an issue. To me it is that you provided bug report of something that I then debugged and provided that pageno might be the issue on CoverPage. No need to start cursing here if you can't really even provide any backups to your claim. I have quite a lot freetime to start debugging instantly and I get GitHub notifications to my phone, which quite well explains why I have the solution right away too. 

> This conversation is over, go whine somewhere else
>
You are the one who has stated multiple times that end of discussion but yet still can' stand behind your own words. You are also the only one who's whining about something, I'm asking you to provide evidence to backup your claim. Otherwise, you're lying or acting stupid.

**Comment by szopin** [comment]
You came up with: I think I can implement it with pageno all of a suddeb in a normal ping pong style of exchanges, just out of the blue, srsly go somewhere else we don't need liars in this project, if you want me to block you sure, go ahead

On Sunday, 9 August 2020, Santeri wrote:
> > How about you review that thread where you instantly have a possible solution you lying fuck?
> >
> This doesn't provide me anything because I don't see that as an issue. To me it is that you provided bug report of something that I then debugged and provided that pageno might be the issue on CoverPage. No need to start cursing here if you can't really even provide any backups to your claim. I have quite a lot freetime to start debugging instantly and I get GitHub notifications to my phone, which quite well explains why I have the solution right away too. 
> 
> > This conversation is over, go whine somewhere else
> >
> You are the one who has stated multiple times that end of discussion but yet still can' stand behind your own words. You are also the only one who's whining about something, I'm asking you to provide evidence to backup your claim. Otherwise, you're lying or acting stupid. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105158

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> I think I can implement it with pageno all of a suddeb
>
What the heck does this provide? If I start debugging instantly why the hell wouldn't I find out the solution quite quickly? Yet again this doesn't provide any information...
> srsly go somewhere else we don't need liars in this project, if you want me to block you sure, go ahead
>
If you want to block me then go ahead. Couldn't really care less about your blocks, it's no offense to me. But what I do care is that when someone claims something, again, it needs to be backed up in some way. Your way is way too loose and open to subjective opinion so it's not an empirically objective. It's as logical as I would say that you're systematically interpreting my words in that way so that you can make such claim.

**Comment by szopin** [comment]
Literally at the beginning you jumped to: oh sure I can fix it, just need that pageno gone (minutes after bug report), whrn I later said submitting PRs with known bugs you just crued in a corner as you were found out, now you're claiming you're a minority that needs preservation and protection, do that witg your country courts, idgaf

On Sunday, 9 August 2020, Santeri wrote:
> > I think I can implement it with pageno all of a suddeb
> >
> What the heck does this provide? If I start debugging instantly why the hell wouldn't I find out the solution quite quickly? Yet again this doesn't provide any information...
> > srsly go somewhere else we don't need liars in this project, if you want me to block you sure, go ahead
> >
> If you want to block me then go ahead. Couldn't really care less about your blocks, it's no offense to me. But what I do care is that when someone claims something, again, it needs to be backed up in some way. Your way is way too loose and open to subjective opinion so it's not an empirically objective. It's as logical as I would say that you're systematically interpreting my words in that way so that you can make such claim. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105257

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Literally at the beginning you jumped to: oh sure I can fix it, just need that pageno gone (minutes after bug report)
>
This doesn't provide anything objective. Knowing how the applications XMLHttprequests work and knowing that the pageno could cause issues on cover doesn't mean that I intentionally posted buggy PR. 
> now you're claiming you're a minority that needs preservation and protection, do that witg your country courts, idgaf
>
That's very low. By the way where do I claim such thing how did you come up with such manifestation?

**Comment by szopin** [comment]
In literally two minutes you knew, idgaf about courts, just don't fucking lie in my face ok?

On Sunday, 9 August 2020, Santeri wrote:
> > Literally at the beginning you jumped to: oh sure I can fix it, just need that pageno gone (minutes after bug report)
> >
> This doesn't provide anything objective. Knowing how the applications XMLHttprequests work and knowing that the pageno could cause issues on cover doesn't mean that I intentionally posted buggy PR. 
> > now you're claiming you're a minority that needs preservation and protection, do that witg your country courts, idgaf
> >
> That's very low. By the way where do I claim such thing how did you come up with such manifestation?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105331

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> In literally two minutes you knew
> 
Sure. Because I was on my computer with all the development stuff open already? 
> idgaf about courts, just don't fucking lie in my face ok?
>
What the heck do you mean? What courts? Do you really think something is going to court? I could claim the same thing that don't lie or even better don't manifest something that you don't have any clear objective argument behind that.

**Comment by szopin** [comment]
'Two minutes is all I need to know I submitted a buggy code' 
Nice, it even rhymes

On Sunday, 9 August 2020, Santeri wrote:
> > In literally two minutes you knew
> > 
> Sure. Because I was on my computer with all the development stuff open already? 
> > idgaf about courts, just don't fucking lie in my face ok?
> >
> What the heck do you mean? What courts? Do you really think something is going to court? I could claim the same thing that don't lie or even better don't manifest something that you don't have any clear objective argument behind that. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105377

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> 'Two minutes is all I need to know I submitted a buggy code'
Nice, it even rhymes
>
So it seems yeah. But that isn't constructive, is it?

**Comment by szopin** [comment]
Sending buggy code is also not constructive (the idiot will have to review/fix the pos I submitted haHAA
Like ffs don't pretend to be unrelated.again, fuck this shit

On Sunday, 9 August 2020, Santeri wrote:
> > 'Two minutes is all I need to know I submitted a buggy code'
> Nice, it even rhymes
> >
> So it seems yeah. But that isn't constructive, is it? 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105416

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Sending buggy code is also not constructive
>
Sending no code at all is not constructive. We have way different opinion on what's "buggy". But that's what you get, I bet no real developers can write code during their career and never "send buggy code". I never send something with an attitude that some "the idiot will have to review/fix the pos I submitted haHAA".
> Like ffs don't pretend to be unrelated.again, fuck this shit
> 
Not pretending anything. It's just funny how you make statements that you can't objectively backup because you interpret something in a way. Then when the same thing is pointed to you, you deny it. You contradict yourself by that.

**Comment by szopin** [comment]
Just fucking stop dude, noone wants your code ok? Just stop? Do I need to write: 'you're too autistic to add to our codebase' like corps do? Just be on your way, cya

On Sunday, 9 August 2020, Santeri wrote:
> > Sending buggy code is also not constructive
> >
> Sending no code at all is not constructive. We have way different opinion on what's "buggy". But that's what you get, I bet no real developers can write code during their career and never "send buggy code". I never send something with an attitude that some "the idiot will have to review/fix the pos I submitted haHAA".
> > Like ffs don't pretend to be unrelated.again, fuck this shit
> > 
> Not pretending anything. It's just funny how you make statements that you can't objectively backup because you interpret something in a way. Then when the same thing is pointed to you, you deny it. You contradict yourself by that. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105486

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Just fucking stop dude, noone wants your code ok? Just stop? Do I need to write: 'you're too autistic to add to our codebase' like corps do? Just be on your way, cya
>
Why can't you just stop if it's so big a deal to you to answer to these? I stop when I want to stop. Write whatever you want to write, certainly won't do anything good to you. It's quite funny that "No one wants your code ok?" but at the same time I'm working with code and contributed to this repository but yet still no one wants my code. Contradiction.

**Comment by szopin** [comment]
You're just awkward? Look this:
I stop when I want to stop. Write whatever you want to write, certainly won't do anything good to you. It's quite funny that "No one wants your code ok?" but at the same time I'm working with code and contributed to this repository but yet still no one wants my code.
Is not a white flag to behave like a lunatic, but it's what you do. Just good luck

On Sunday, 9 August 2020, Santeri wrote:
> > Just fucking stop dude, noone wants your code ok? Just stop? Do I need to write: 'you're too autistic to add to our codebase' like corps do? Just be on your way, cya
> >
> Why can't you just stop if it's so big a deal to you to answer to these? I stop when I want to stop. Write whatever you want to write, certainly won't do anything good to you. It's quite funny that "No one wants your code ok?" but at the same time I'm working with code and contributed to this repository but yet still no one wants my code. Contradiction.  
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105543

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> You're just awkward?
>
What's your point / goal labeling me all the time by some names or characteristics? Do you think it makes you any better than your self claimed "lunatic". 
> Just good luck
> 
Just good luck for you too? Never really wanted any harm to you. But what I don't get is the whining and your victimhood of time taking and pushing "buggy code" etc. The thing is just that you don't like me, don't really care what psychological stuff there happens, am I threat to you etc.

**Comment by szopin** [comment]
Good luck lunatic

On Sunday, 9 August 2020, Santeri wrote:
> > You're just awkward?
> >
> What's your point / goal labeling me all the time by some names or characteristics? Do you think it makes you any better than your self claimed "lunatic". 
> > Just good luck
> > 
> Just good luck for you too? Never really wanted any harm to you. But what I don't get is the whining and your victimhood of time taking and pushing "buggy code" etc. The thing is just that you don't like me, don't really care what psychological stuff there happens, am I threat to you etc.  
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105642

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin, I think it might be wise to remove these comments from this repository, or what do you think? You can certainly develop your app in a way that you want. Not going to "interfere" any longer since there's too much friction between us.

**Comment by szopin** [comment]
Why don't you heed your own comments advice?

On Sunday, 9 August 2020, Santeri wrote:
> @szopin, I think it might be wise to remove these comments from this repository, or what do you think? You can certainly develop your app in a way that you want. Not going to "interfere" any longer since there's too much friction between us.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67105982

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
> Why don't you heed your own comments advice?
>
What do you mean by that? Then again it doesn't seem to help with my question. If you really think that it's good to have them here then let's go with that.

**Comment by szopin** [comment]
Do you seriously think anyone would let you the snake into any part of code? Kek, you're really retired

On Sunday, 9 August 2020, Santeri wrote:
> > Why don't you heed your own comments advice?
> >
> What do you mean by that? Then again it doesn't seem to help with my question. If you really think that it's good to have them here then let's go with that. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67106056

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Look: noone will vouch for you noone likes you, you're just a blimp of an sdk target, noone gives a fuck about your existence, but pretend to be someone 

On Sunday, 9 August 2020, Santeri wrote:
> > Why don't you heed your own comments advice?
> >
> What do you mean by that? Then again it doesn't seem to help with my question. If you really think that it's good to have them here then let's go with that. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67106056

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
Okay then. Must've bitten you quite well to you going in a ranting mode

**Comment by szopin** [comment]
Sure dude, we made special.case for you calling: mommy! And outside of that get fucked, you have literally nothing except: this space between labels should be extra +25pixels ok?

On Sunday, 9 August 2020, Santeri wrote:
> Okay then. Must've bitten you quite well to you going in a ranting mode
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67106157

-- 
Sent from my Jolla

**Comment by szopin** [comment]
"Must've bitten you quite well" lol explain, all

> 
> 
> Okay then. Must've bitten you quite well to you going in a ranting mode

Bitten? All you do is submit code, shitty code with 'wireframe' (which are not wireframes, learn the difference) approaches (which are just your emulator burps), then you complain when the shit you submitted is not on par of any other code (multiple bugs, works not like described etc), then you claim you're being harassed... Dude, how about you submit a worthwhile piece of code or nothing? I'm fine with both, if you want to just complain, go ahead but without me, if you want to add something to the codebase I will support you. Otherwise see ya while you claim raycisst code review that fucked your piece out of the shit

**Comment by szopin** [comment]
Apparently there is a JS function that does it, will eventually find it, the keeper of knowledge (I got it working, I can do X or Y... woohoo) can do things to himself, I don't care, this is being closed for now (if you know which exactly function he meant... go ahead and reopen)

**Comment by Moppa5** [comment]
@szopin, I can more than willingly provide what I used on implementation since I like this app myself. Again, no need to regress to childlike behavior of interpreting or characterizing actions when you could just simply ask. 

JavaScript date formatter provides nice way to format dates. This similar formatDate can also be used to have lots of other Formatter methods like for dates in general.

Just add the wanted date to replace the last_activity. I used the JSON timestamps for this so no need to format anything before creating new date. 
```
var latestTime = new Date(last_activity)
var formatted = Format.formatDate(latestTime, Formatter.DurationElapsedShort)
```

**Comment by szopin** [comment]
Thanks dude, appreciate it

**Comment by szopin** [comment]
I've asked you multiple times, i don't really care, thanks for sharing, still doesn't fix the beef we have between us does it

On Sunday, 9 August 2020, Santeri wrote:
> @szopin, I can more than willingly provide what I used on implementation since I like this app myself. Again, no need to regress to childlike behavior of interpreting or characterizing actions when you could just simply ask. 
> 
> JavaScript date formatter provides nice way to format dates. This similar formatDate can also be used to have lots of other Formatter methods like for dates in general.
> 
> Just add the wanted date to replace the last_activity. I used the JSON timestamps for this so no need to format anything before creating new date. 
> ```
> var latestTime = new Date(last_activity)
> var formatted = Format.formatDate(latestTime, Formatter.DurationElapsedShort)
> ```
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/13#issuecomment-67108020

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin, I don't think you've explicitly asked here to provide the code for that. However, if you have well not it's provided to you. The fix for sort of "beef between us" is not to develop anything together. Thus I won't be contributing here any longer.

**Comment by szopin** [comment]
> 
> 
> @szopin, I don't think you've explicitly asked here to provide the code for that. However, if you have well now it's provided to you. The fix for sort of "beef between us" is not to develop anything together. Thus I won't be contributing here any longer.

Awesome, I just wonder why it took you sooooo freaking long (54th comment in this thread alone), cya dude

**Comment by Pohli** [comment]
Thank you very much, just updated, this helps alot now that I have a clue where to start reading without switching to web browser first.
