### ISSUE TITLE
Cover refresh function doesn't reload main page

### ISSUE THREAD

**Issue by Pohli** [szopin/harbour-sfos-forum-viewer#15]
See title.

Jolla Phone with SFOS 3.0.1.11 and SFOS Forum Viewer 0.7.4

**Comment by szopin** [comment]
It does, except if you 'loaded more' then it only refreshes the 2nd or third etc page, author of the PR was aware of that, haven't had yet the time to fix it

**Comment by Pohli** [comment]
Just tested again after a reboot: loaded SFOS Forum in Fennec to compare (Latest view), started SFOS Forum Viewer (also latest view), checked topic order, back to SFOS cover view, app cover showed the right topics, too. Waited for updated topic had moved to top in Fennec, tapped refresh button on app cover, cover topic list successfully updated, opened SFOS Forum Viewer, topic list not updated yet, had to use Reload option from pulley menu. And that's what I mean, I haven't used Load more feature.

**Comment by szopin** [comment]
Oh, not sure if a bug then, cover action shouldn't really override inApp functionality, so if you're in a middle of a thread in the app, reloading from cover shouldn't throw you out to threadsview with new results (and not really sure how to preserve the position you went into the thread from if it was last it no longer exists in the listview as it could get bumped out of the list, or it could get bumped from last to first, so again navigating back would now be bugged)

**Comment by Moppa5** [comment]
@Pohli, this is not explicitly a bug but rather it's definitely inconvenient. On the other hand, I don't think this is such a big deal. Currently the issue is due to the cover fetching data separately when comparing the main view. 

@szopin, By the way I don't think that populating the model would really throw you away from the thread that's opened since the page has been pushed and QML components have been loaded before. So basically it seems that it can't fetch any new data based on that thread but if the thread is loaded you can certainly browse it.  To put it shortly, actions on that thread wouldn't work properly.

**Comment by szopin** [comment]
I'm decoupling cover from inApp actions in .7.5 so only latest are shown in cover, cover not following user to top/categories should be clear indication that it only has latest view as I think originally intended with 'latest post' or whatever it was title (refreshing top is totally useless, per category is also kinda useless as the forum is slow enough, simple 10 latest threads should also not generate any extra bugs to worry about)

On Sunday, 9 August 2020, Santeri wrote:
> @Pohli, this is not explicitly a bug but rather it's definitely inconvenient. On the other hand, I don't think this is such a big deal. Currently the issue is due to the cover fetching data separately when comparing the main view. 
> 
> @szopin, By the way I don't think that populating the model would really throw you away from the thread that's opened since the page has been pushed and QML components have been loaded before. So basically it seems that it can't fetch any new data based on that thread but if the thread is loaded you can certainly browse it.  To put it shortly, actions on that thread wouldn't work properly. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/15#issuecomment-67102555

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin, I have just fixed the CoverPage "Load More" bug. Will I make PR or abort this? I think that I could have taken a look at this issue too so that refreshing on CoverPage would have an action on the main view too but not to throw user out of a thread if it's open.

**Comment by szopin** [comment]
No thanks, have it already doing what I want on phone, throwing out of thread view is not the the issue but thread you went into either shifting position or totally disappearing (if you say are viewing thread 20 and new topic gets posted, we'll get a new issue then pls keep my thread on the page)

On Sunday, 9 August 2020, Santeri wrote:
> @szopin, I have just fixed the CoverPage "Load More" bug. Will I make PR or abort this? I think that I could have taken a look at this issue too so that refreshing on CoverPage would have an action on the main view too but not to throw user out of a thread if it's open. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/15#issuecomment-67102659

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin Again, it won't change the pushed page thread at all (no shifting positions or disappearings) since the QML components and the content have already been loaded. Unless you can make realistic situation of the user opening a thread and refreshing the cover at the same time before the JSON parse and model population have been done. 

Nevertheless, I'll stash the cover fixes if they're not needed.

**Comment by szopin** [comment]
Open last thread from latest view, minimize app, wait an hour so it gets bumped out, refresh from cover - go back into application, once you navigate back the thread is no longer there =  submit an issue as it's confusing and we should definitely track which thread user is coming back from scrolling to it if it got bumped from last pos to 1st (that's also confusing) or load more as long as needed to be able to scroll if it got bumped out... Pass

On Sunday, 9 August 2020, Santeri wrote:
> @szopin Again, it won't change the pushed page thread at all (no shifting positions or disappearings) since the QML components and the content have already been loaded. Unless you can make realistic situation of the user opening a thread and refreshing the cover at the same time before the JSON parse and model population have been done. 
> 
> Nevertheless, I'll stash the cover fixes if they're not needed.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/15#issuecomment-67102937

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Btw at this moment this might sound like a non-issue, but if you scrolled 20 times down 'load more' losing your position is kinda bad, being able to keep track from cover of what's happening is an extra feature in a way (once they import all tjc threads could become reality - the 20x 'load more' I mean, there's hundreds if not thousands of threads coming from 7 years or so)

On Sunday, 9 August 2020, Santeri wrote:
> @szopin Again, it won't change the pushed page thread at all (no shifting positions or disappearings) since the QML components and the content have already been loaded. Unless you can make realistic situation of the user opening a thread and refreshing the cover at the same time before the JSON parse and model population have been done. 
> 
> Nevertheless, I'll stash the cover fixes if they're not needed.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/15#issuecomment-67102937

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Cover is now only for 'latest posts', no matter what page or thread you have open in app, I think it fixes that
