### ISSUE TITLE
Preformatted text is partly hidden

### ISSUE THREAD

**Issue by Pohli** [szopin/harbour-sfos-forum-viewer#16]
I can't read preformatted text in a post completely cause the part beyond the right edge is unreachable. In the browser version preformatted text is fully accessible by horizontal scrolling (in Fennec, my old Jolla Browser has the same problem).
For example see topic: [Can't call/Audio not working](https://forum.sailfishos.org/t/cant-call-audio-not-working/1421)

Jolla Phone with SFOS 3.0.1.11 and SFOS Forum Viewer 0.7.4

**Comment by szopin** [comment]
I'm afraid open in webview/browser will have to work as a workaround, seen how quickddit does it and it's buggy as hell (the horizontal scroll causes half of the clicks to incorrectly register and you can get stuck in the middle of a long code post which hardly ever scrolls as half of the clicks get lost), without reparsing the whole richtext and manually wrapping... yeah not something we'll do anytime soon. If you've seen an app that does it properly pls reopen, might reinvestigate it then
