### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by ichthyosaurus** [szopin/harbour-sfos-forum-viewer#19]
It would be much easier to work with the code if it were better formatted. QtCreator can apply automatic formatting (which is okay most of the time): select all text and press Ctrl+i.

(You can also apply real formatting instead of only indentation by going to Extras > QML/JS > Reformat file. This is not perfect though, in my experience. It needs quite a lot of work afterwards. Proper indentation would already help a lot without much manual clean up.)

**Comment by szopin** [comment]
Heh, yeah I know, but as I work on this 99% on the phone and end up being just lazy and copying over whatever managed to work... Yeah I'll try to re-indent it afterwards, but it's probably gonna get messy soon anyway again

**Comment by szopin** [comment]
Fixed for now in latest commit, but will probably not last long

**Comment by ichthyosaurus** [comment]
Uh oh, you're coding on your phone... Anyway, thanks for the nice app :)!
