### ISSUE TITLE
Spanish translation not work.

### ISSUE THREAD

**Issue by GNUuser** [szopin/harbour-sfos-forum-viewer#23]
version 8.2 seems not work es-translations.

**Comment by szopin** [comment]
Doesn't seem to have language="es_ES", did you select the correct language in Qt linguist?

**Comment by GNUuser** [comment]
It is not a issue es_ES, i guess it is a issue in es.ts files. I am working to find it.

**Comment by GNUuser** [comment]
@szopin can you refresh all *.ts files please.

**Comment by szopin** [comment]
Parse error at /home/mersdk/share/sfv/harbour-sfos-forum-viewer/translations/harbour-sfos-forum-viewer-es.ts:204:38: Unexpected '<'.

            <numerusform>%n gusta(s)<</numerusform>

**Comment by GNUuser** [comment]
Yeah, but all ts files are not sync, so update all ts files.

**Comment by szopin** [comment]
I'm guessing this is just the double <<... can you check if it works with 1?

**Comment by szopin** [comment]
On my side it works:
Updating 'translations/harbour-sfos-forum-viewer-de.ts'...
    Found 34 source text(s) (0 new and 34 already existing)
Updating 'translations/harbour-sfos-forum-viewer-en.ts'...
    Found 34 source text(s) (0 new and 34 already existing)
Updating 'translations/harbour-sfos-forum-viewer-es.ts'...
    Found 34 source text(s) (0 new and 34 already existing)

Can you check if it actually displays in spanish? Don't think emulator supports that

**Comment by GNUuser** [comment]
Can you push a new version in openrepos to check if work. i am not a home to run SDK

**Comment by szopin** [comment]
Fixed

**Comment by GNUuser** [comment]
> Fixed

Thank you. It work!
