### ISSUE TITLE
Add some  string to be translatable. 

### ISSUE THREAD

**Issue by GNUuser** [szopin/harbour-sfos-forum-viewer#26]
![Captura_20200816_002](https://user-images.githubusercontent.com/45316884/90344455-f9d2c280-dfe7-11ea-8213-6e02466e8c50.png)

**Comment by GNUuser** [comment]
Like Beginners, annuncements, applications, more, more, this string coming from API?

**Comment by szopin** [comment]
Those are all from API

**Comment by szopin** [comment]
I'm going to close this for now, really not sure if we can fix it, the categories can and will grow over time (there's like 5-10 proposed new ones), if it stabilises in theopry we could have our own list in swl and translate on the go... but is it even worth it
