### ISSUE TITLE
Referenced post's can't be open in the forum gui

### ISSUE THREAD

**Issue by yajo10** [szopin/harbour-sfos-forum-viewer#51]
Hi,
thanks for your great work!
I nevertheless have a suggestion:
in a lot of threads there are some referenced threads that can only be shown in the webview or opened externaly. 
Suggestions:
linked threads are opened in the normal gui. 
Example:
This [link](https://forum.sailfishos.org/t/announcing-sailfishos-chum/7381/77) to another thread can't be opened in the gui.
Thank's in advance!

**Comment by szopin** [comment]
Fixed in 0.9.12
