### ISSUE TITLE
Move category selection to open in a panel view

### ISSUE THREAD

**Issue by Moppa5** [szopin/harbour-sfos-forum-viewer#6]
**Description**
Posting this as an issue since this needs further planning and possible improvements. I've been working on with moving category selection to open as a panel view on the main forum thread view (see the screenshots below, it explains more). Currently I've connected the panel similarly as the current "Browse by category" => PullDownMenu to unify and make the transition more smooth. In my opinion this enhancement would make the application seem more dynamic and remove excess PageStack pushing.

**Questions on implementations and use cases**
- What kind of background we should use? Better color ideas? Images?
- Comments on alignment of the panel view?
- How would you prefer the panel opening? PullDownMenu item as normally or something else for instance?

**Screenshots**
Currently implemented WIP version. One enhancement that I find immediately is that the title "Categories" could be aligned left as the others
![post_image](http://puu.sh/GcFG9/ee0fdb19d0.jpg)

**Comment by szopin** [comment]
Not really sure about side panels, seen them in the IRC app and not a big fan, if you want to reduce the top menu could move that to attachedpage, though it probably will have some more use once/if we reach 2.0. btw I don't think we have any excess of pagestack pushing as selecting category clears the stack, or did I misunderstand that part

**Comment by Moppa5** [comment]
Alright, well this surely is preference opinion. Yet still you could try it if you haven't already and then report how it looks on your device. By the excess pagestack pushing I meant that there's the visual response of pushing between pages, which of course could be removed f wanted.

**Comment by szopin** [comment]
There's a handful of apps that use side panels (literally one I can recall is irc) and it just doesn't really flow that well (also touch-swipe detection was wonky with scrollable area in the middle), I really think if you want to declutter top menu attachedPage would do the trick (and no need to worry about background color etc), quickddit does it for subreddits page from which you access also profile specific items so users of it would feel at home? Idk, maybe we should start a thread on the forum itself, no sure if it supports polls, but would be easier to gauge user feelings with likes at least. Sorry to ping you @elros34 but would love your opinion too

On Friday, 31 July 2020, Santeri wrote:
> Alright, well this surely is preference opinion. Yet still you could try it if you haven't already and then report how it looks on your device. By the excess pagestack pushing I meant that there's the visual response of pushing between pages, which of course could be removed f wanted. 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/6#issuecomment-66707687

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin Anyway, thank you for your feedback. Have you already tried this on your (I assume) Jolla C? I agree that I've seen also apps where there have been issues with scrolling or toggling this but this feature would use Sailfish Silica components and you can't drag the panel view there so no swiping wonky exists. Personally I prefer that the top menu would be simple as possible, so quick toggles like "latest" etc. can surely stay there but we should avoid too many new page actions there. This needs more planning and further development. 

Btw, Are you already implementing the attachedPage feature?

**Comment by szopin** [comment]
That assumes the category list will stay static and there are quite a few suggestions aleady, so we'll see. Check the quickddit approach, it also doesn't have a lightbar on the side all the time, just a dot indicating there's more when at the top of the page (we could also squeeze things like login/account options/messages etc there IF we ever get there). Haven't had any free time this week yet, might be able to squeeze in 'search thread' option today or tomorrow, we'll see.  

On Sunday, 2 August 2020, Santeri wrote:
> @szopin Anyway, thank you for your feedback. Have you already tried this on your (I assume) Jolla C? I agree that I've seen also apps where there have been issues with scrolling or toggling this but this feature would use Sailfish Silica components and you can't drag the panel view there so no swiping wonky exists. Personally I prefer that the top menu would be simple as possible, so quick toggles like "latest" etc. can surely stay there but we should avoid too many new page actions there. This needs more planning and further development. 
> 
> Btw, Are you already implementing the attachedPage feature? 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/6#issuecomment-66764880

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin You don't literally get my point, do you? First of all, what do you mean by "That assumes the category list will stay static", I didn't quite catch that since it has a SilicaListView to populate categories based on a model. And the second, what do you mean "it also doesn't have a lightbar on the side all the time"? Did you even compile my fork and took a look at how it really was? There's literally no lightbar there. 

The use case would be very similar than the current one:
- User navigates to PullDownMenu / TopMenu
- User toggles "Browse by category"
- The side panel view is opened
- User picks the wanted category

On the other hand, I took a look at the Quickddit Reddit client and not really sure if it's significantly better than our current implementation.

**Comment by szopin** [comment]
If they add more categories it will become scrollable, so could result in usability issues. If you want to keep the trigger in pulleymenu then i have no idea what the point is as it doesn't declutter top menu, having it behind a swipe ala quickddit actually does reduce the top menu by 1 option. (lightbar will be visible if you want to have a side panel available all the time (without top menu access) and it just looks ugly) 

On Sunday, 2 August 2020, Santeri wrote:
> @szopin You don't literally get my point, do you? First of all, what do you mean by "That assumes the category list will stay static", I didn't quite catch that since it has a SilicaListView to populate categories based on a model. And the second, what do you mean "it also doesn't have a lightbar on the side all the time"? Did you even compile my fork and took a look at how it really was? There's literally no lightbar there. 
> 
> The use case would be very similar than the current one:
> - User navigates to PullDownMenu / TopMenu
> - User toggles "Browse by category"
> - The side panel view is opened
> - User picks the wanted category
> 
> On the other hand, I took a look at the Quickddit Reddit client and not really sure if it's significantly better than our current implementation. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/6#issuecomment-66765174

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
My point was never really to reduce the topmenu. Rather my point was to make the forum posts view more dynamic by not having to push between pages so that you can browse categories. 

Nevertheless, due to your reluctance on the feature, you might as well close this issue.

**Comment by szopin** [comment]
There is no pushing, you click on category and it loads without any extra pagestack, side menu just makes the clickable area lower (in this case whole of the right side of the screen does nothing so making it less usable to left-handed people for no return), don't see how this is more dynamic, thought your goal was to declutter top menu as that is an issue and with every new functionality added it has to be taken into account, but just replacing a page with side panel doesn't really add anything in terms of usability and seems like a gimmick 

On Sunday, 2 August 2020, Santeri wrote:
> My point was never really to reduce the topmenu. Rather my point was to make the forum posts view more dynamic by not having to push between pages so that you can browse categories. 
> 
> Nevertheless, due to your reluctance on the feature, you might as well close this issue. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/6#issuecomment-66765395

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Closing for now, if there are arguments to reimplement category view (probably will be once more pages and options are needed in the future) feel free to reopen
