### ISSUE TITLE
Feature Request: support "hidden" (read restricted) categories

### ISSUE THREAD

**Issue by nephros** [szopin/harbour-sfos-forum-viewer#60]
Description:

The Forum has "secret" or hidden categories (e.g. the "Lounge", category id 4), but these are not displayed or select-able in the Categories view.

Also, posts from these categories do not show up in the "latest topics" overview.

(Accessing them works when e.g. a notification is sent from a post in one of those categories, and one clicks on that.)

**Comment by nephros** [comment]
From quickly skimming the QML code, I believe the reason for this is that the categories model is loaded unauthenticated. Therefore only public categories are available in the app.

Maybe the fix is simply to refresh the categories after authentication, or if a user auth key exists, use that when requesting https://forum.sailfishos.org/categories.json

**Comment by nephros** [comment]
The same should apply to [fetchlatestposts()](https://github.com/szopin/harbour-sfos-forum-viewer/blob/master/qml/harbour-sfos-forum-viewer.qml#L106), which is also done unauthenticated.

**Comment by szopin** [comment]
Wow, didn't know these exist, will have a look

On Wednesday, 18 January 2023, Peter G. wrote:
> Description:
> 
> The Forum has "secret" or hidden categories (e.g. the "Lounge", category id 4), but these are not displayed or select-able in the Categories view.
> 
> Also, posts from these categories do not show up in the "latest topics" overview.
> 
> (Accessing them works when e.g. a notification is sent from a post in one of those categories, and one clicks on that.) 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/60
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Doesn't work, looks like you need to be invited/allowed, you can just add:
if (loggedin.value != "-1") xhr.setRequestHeader("User-Api-Key", loggedin.value);
To the two functions and also:
import Nemo.Configuration 1.0
And somewhere in the middle:
ConfigurationValue {
        id: loggedin
        key: "/apps/harbour-sfos-forum-viewer/key"
    }
To get them to use authorized flow, but I'm not getting any secret categories or posts, not going to add this blindly as it might break other things, someone from 'the clique' will need to create a PR ;)

On Wednesday, 18 January 2023, Peter G. wrote:
> The same should apply to [fetchlatestposts()](https://github.com/szopin/harbour-sfos-forum-viewer/blob/master/qml/harbour-sfos-forum-viewer.qml#L106), which is also done unauthenticated.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/60#issuecomment-1386833545
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by nephros** [comment]
Yes, playing around with things in https://github.com/szopin/harbour-sfos-forum-viewer/commit/8a5852c902d77d66efc09568f6fe28c0bca804bd and follow-ups.

The categories show up with this, but they do not load anything.

I'll have to look through all the XHRs, presumably most of them need the api key set IF they refer to something from such a hidden category.

**Comment by szopin** [comment]
FirstPage probably needs that configvalue (or are those global?), updateview() probably is the one that needs that header too

On Wednesday, 18 January 2023, Peter G. wrote:
> Yes, playing around with things in https://github.com/szopin/harbour-sfos-forum-viewer/commit/8a5852c902d77d66efc09568f6fe28c0bca804bd and follow-ups.
> 
> The categories show up with this, but they do not load anything.
> 
> I'll have to look through all the XHRs, presumably most of them need the api key set IF they refer to something from such a hidden category.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/60#issuecomment-1386901551
> You are receiving this because you commented.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Yeah updateview() in firstpage should be enough as getcomments in threadview already has that, the lounge should be visible if it's top category as only those are implemented if it's a subcategory like c++/qml etc it would need a slight rewrite

On Wednesday, 18 January 2023, Peter G. wrote:
> Yes, playing around with things in https://github.com/szopin/harbour-sfos-forum-viewer/commit/8a5852c902d77d66efc09568f6fe28c0bca804bd and follow-ups.
> 
> The categories show up with this, but they do not load anything.
> 
> I'll have to look through all the XHRs, presumably most of them need the api key set IF they refer to something from such a hidden category.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/60#issuecomment-1386901551
> You are receiving this because you commented.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by nephros** [comment]
> if it's a subcategory like c++/qml etc it would need a slight rewrite

See #61 about that.

**Comment by nephros** [comment]
https://github.com/nephros/harbour-sfos-forum-viewer/tree/authload

This seems to work so far, could be a couple of things are missing.

**Comment by szopin** [comment]
Looks good, just make sure to include the 'if' in updateview or it will break the app for logged out people

**Comment by szopin** [comment]
hmmm, the 'if's in the main qml file probably also need '&& loggedin.value)' as the -1 is set from FirstPage on first run, so it might break the first run of the app
