### ISSUE TITLE
Bug/Feature request: Handling of Sub-Categories

### ISSUE THREAD

**Issue by nephros** [szopin/harbour-sfos-forum-viewer#61]
The Forum has subcategories for some categories.

The only one I know of is category 5 / "Applications".

In https://forum.sailfishos.org/categories.json you can see that (abridged):

```
{
        "id": 5,
        "name": "Applications",
        "slug": "app-development",
        "has_children": true,
        "subcategory_ids": [
          6,
          7,
          8
        ]
}
```

This isn't critical, but I can see the following issue:

 - qml warning: `/qml/pages/FirstPage.qml:496  file:///home/nemo/devel/git/_forks/harbour-sfos-forum-viewer/qml/pages/FirstPage.qml:496: TypeError: Cannot read property 'name' of undefined`
   - this is because the category ID of the topic is 7, but the category model only knows about 5.  
   - this is visible in the UI i that the post has a color, but no category name visible.
   - example post showing the issue: https://forum.sailfishos.org/t/14129/3

**Comment by szopin** [comment]
Yeah those are the ones missing proper implementation, as it's just 3 never bothered rewriting this

On Wednesday, 18 January 2023, Peter G. wrote:
> The Forum has subcategories for some categories.
> 
> The only one I know of is category 5 / "Applications".
> 
> In https://forum.sailfishos.org/categories.json you can see that (abridged):
> 
> ```
> {
>         "id": 5,
>         "name": "Applications",
>         "slug": "app-development",
>         "has_children": true,
>         "subcategory_ids": [
>           6,
>           7,
>           8
>         ]
> }
> ```
> 
> This isn't critical, but I can see the following issue:
> 
>  - qml warning: `/qml/pages/FirstPage.qml:496  file:///home/nemo/devel/git/_forks/harbour-sfos-forum-viewer/qml/pages/FirstPage.qml:496: TypeError: Cannot read property 'name' of undefined`
>    - this is because the category ID of the topic is 7, but the category model only knows about 5.  
>    - this is visible in the UI i that the post has a color, but no category name visible.
>    - example post showing the issue: https://forum.sailfishos.org/t/14129/3
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/61
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla
