### ISSUE TITLE
Long titles are overflowing 

### ISSUE THREAD

**Issue by Moppa5** [szopin/harbour-sfos-forum-viewer#7]
**Description**
Some long titles, for instance in attached screenshot, are overflowing away because the pageheader doesn't have any wrapping. 

**Screenshots**
Without any wrapping
![image](http://puu.sh/GcGgU/3809f38f5a.jpg)

With wrapping
![image_wrap](http://puu.sh/GcGjj/12f0592d87.jpg)

What do you think? Is this something that we should concern ourselves and easily fix by adding the wrap properties or should we leave it be?

**Comment by szopin** [comment]
I don't really think we need to see the full category title (or the same in threadview, it's just there so you know which title you clicked), eats way too much of screen space for very little gain imho, we'd need to make the font much smaller based on title length... really not sure, beginning seems good enough to know you haven't misclicked

**Comment by Moppa5** [comment]
@szopin Yeah, this was something that I though too but wanted to ask some opinion about the case. You can close this issue and maybe put some label like "Won't fix" if you want to. Not maybe something that we need to develop.

**Comment by szopin** [comment]
Not sure how to tag it WONTFIX but just closing for now, if someone has a good idea that looks good and also doesn't eat screenspace please reopen

**Comment by Moppa5** [comment]
@szopin There's the "Labels" section on every GitHub issue on the same right side bar where you can assign people on to the issue. There should be multiple tags like for instance bug and one of these labels is the "wontfix" one which I meant.

**Comment by szopin** [comment]
Thanks! Will check when I get to a functional browser :)

On Sunday, 2 August 2020, Santeri wrote:
> @szopin There's the "Labels" section on every GitHub issue on the same right side bar where you can assign people on to the issue. There should be multiple tags like for instance bug and one of these labels is the "wontfix" one which I meant.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/7#issuecomment-66764909

-- 
Sent from my Jolla

**Comment by Pohli** [comment]
Another opinion from me: I don't like if there's something beyond visible area but not reachable. Isn't there something in Silica similar to tool tips on a desktop systems? Then you could reveal the hidden text by tapping on the title without wasting space.
