### ISSUE TITLE
Add latest posts or something for CoverPage

### ISSUE THREAD

**Issue by Moppa5** [szopin/harbour-sfos-forum-viewer#9]
**Description**
Sailfish is known for its multitasking thus Jolla themselves recommends to have something interactive on CoverPages too. I think we could implement something like latest posts for instance to the forum viewer coverpage. 

**Screenshots**
I was personally thinking about this "latest posts" possibility. Maybe even add the refresh icon to have some functionality.
![image](http://puu.sh/GdCxB/5c1f07a0f9.jpg) ![image](http://puu.sh/GdCy4/776f96b0be.jpg)

**Current question / issue**
The issue implementing this is that the current model uses FirstPage.qml updateview() function to fetch the first 4 forum posts to another model but the question is how to connect the refresh button on coverpage to this updateview? Sure we could implement another script for instance on ApplicationWindow interface that would fetch the "latest posts" only. Does anyone know how we could use the updateview()? I've read about QML Javascript bindings but it doesn't seem to fit the purpose straight a way.

**Comment by szopin** [comment]
This sounds awesome. Sadly I've never delved into coverpage functionality so have no idea what is needed, if you need to pull out updateview from firstpage to some kind of modules.qml or whatever go ahead (or just copy the current one into the coverpage, will just need updating when the views change, though that shouldn't happen that often, especially not for the limited view from cover)
